title: Pew Research Center - Spring Survey 2022
description: Raw data was obtained from https://www.pewresearch.org/global/dataset/spring-2022-survey-data/
show_downloads: TRUE
theme: jekyll-theme-minimal
